---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ontravelazores/public_html/
    - /bin/cp -fR ./wp-content/themes/citytours-child/* /home/ontravelazores/public_html/wp-content/themes/citytours-child

